In [1]:
#1.Create a vector or array of 100 elements. Its 50th value should be    50.0 and other values should be 0.0 (1 mark)
import numpy as np
a=np.zeros(100)
a[49]=50.0
print(a)

[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.  50.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [233]:
#2.Create a vector or array of 100 elements. Its 50th value should be    10.0 and other values should be 1.0 (1 mark)
a=np.ones(100)
a[49]=10.0
print(a)

[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.  10.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.]


In [6]:
#3.Create a  vector or array whose values are from 3, 30 (1 mark)
a=np.arange(3,31)
print(a)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27
 28 29 30]


In [12]:
#4.X = (1,2,3,4,5).  Reverse and print X (1 mark)
X = (1,2,3,4,5)
a=np.array(X)
X=tuple(a[::-1])
print(X)

(5, 4, 3, 2, 1)


In [14]:
#5.Create a 5x 5 matrix and values should be from 0 to 24 (1 mark)
a=np.arange(25).reshape(5,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6.Consider the following  matrix A1 and A2   (9 marks)


       A1 :
             1        3       0

             2        1        1

             3        4         0

       A2 :
             3        4         6
   
             2        1          3

             1        2          8



In [269]:
#6.a) Find min. max of the values for A1 and A2
A1=np.array([[1,3,0],[2,1,1],[3,4,0]])
A2=np.array([[3,4,6],[2,1,3],[1,2,8]])
print('Max in A1:',A1.max(),'\tMax in A2:',A2.max())
print('Min in A1:',A1.min(),'\tMin in A2:',A2.min())

Max in A1: 4 	Max in A2: 8
Min in A1: 0 	Min in A2: 1


In [270]:
#6.b) Find the mean value for A1 and A2
print('Mean of A1',A1.mean())
print('Mean of A2',A2.mean())

Mean of A1 1.66666666667
Mean of A2 3.33333333333


In [271]:
#6.c) Make the values below the diagonal as 0.0 for A1
A1=np.triu(A1,0)
print(A1)

[[1 3 0]
 [0 1 1]
 [0 0 0]]


In [272]:
#6.d) Multiply A1 and A2
print('Multiplication of A1, A2 is:\n',np.multiply(A1,A2))

Multiplication of A1, A2 is:
 [[ 3 12  0]
 [ 0  1  3]
 [ 0  0  0]]


In [273]:
#6.e) What are the common values between A1 and A2
print('Common values in A1 & A2:',np.intersect1d(A1, A2))

Common values in A1 & A2: [1 3]


In [274]:
#6.f) Swap first and 3rd rows of A1
print('Before:\n',A1)
A1[[0,2]] = A1[[2,0]]
print('\nAfter:\n',A1)

Before:
 [[1 3 0]
 [0 1 1]
 [0 0 0]]

After:
 [[0 0 0]
 [0 1 1]
 [1 3 0]]


In [281]:
#6.g) What is the  most frequent numbers from A1 and A2
from scipy import stats
print('Most frequent number in A1:',np.transpose(stats.mode(A1,axis=None)[0][0]))
print('Most frequent number in A2:',np.transpose(stats.mode(A2,axis=None)[0][0]))

Most frequent number in A1: 1.0
Most frequent number in A2: 2


In [282]:
#6.h) Add a column to A1 with values 1 1 1 
one = np.ones((3,4))
one[:,:-1] = A1
A1=one
print(A1)

ValueError: could not broadcast input array from shape (3,4) into shape (3,3)

In [283]:
#6.i) Add a row to A2 with 2 2 2
two = np.full((3,4),2)
two[:,:-1] = A2
A2=two
print(A2)

ValueError: could not broadcast input array from shape (3,4) into shape (3,3)

In [284]:
#7. Write a function for matrix multiplications and additions. Use A1 and A2 to test.[3 marks]
def matrix_opr(a,b,task):
    result1=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]
    result2=[[0,0,0,0],[0,0,0,0],[0,0,0,0]]
    for i in range(len(a)):
        for j in range(len(b[0])):
            result2[i][j] = a[i][j] + b[i][j]
            for k in range(len(b)):
                result1[i][j] += a[i][k] * b[k][j]
                
    if task=='m':
        return result1
    else:
        return result2
print('Matrix multiplication of A1 & A2:\n',matrix_opr(A1,A2,'m'))
print('\nMatrix addition of A1 & A2:\n',matrix_opr(A1,A2,'a'))

Matrix multiplication of A1 & A2:
 [[0.0, 0.0, 0.0, 0.0], [3.0, 3.0, 11.0, 4.0], [9.0, 7.0, 15.0, 8.0]]

Matrix addition of A1 & A2:
 [[3.0, 4.0, 6.0, 3.0], [2.0, 2.0, 4.0, 3.0], [2.0, 5.0, 8.0, 3.0]]


In [285]:
#8. Write a bubble sort program with normal Python  for 10 floating point numbers [3 marks]
def Bubble_Sort(a):
    n = len(a)
    for i in range(n):
        for j in range(0, n-i-1):
            if a[j] > a[j+1] :
                a[j], a[j+1] = a[j+1], a[j]
                
a=[35,56,43,23,87,12,76,18,5]
Bubble_Sort(a)
print ('Sorted array is:',a)

Sorted array is: [5, 12, 18, 23, 35, 43, 56, 76, 87]
