In [13]:
#Question 1
#Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.
import numpy as np
print('Enter numbers in list:',end='')
myList=[int(x) for x in input().split()]
arr=np.array(myList)
print('My Numpy array is:',arr)

Enter numbers in list:5 7 8 
My Numpy array is: [5 7 8]


In [15]:
#Question 2
#Create a 3x3 matrix with values ranging from 2 to 10.
a=np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [18]:
#Question 3
#Write a Python program to create a null vector of size 10 and update sixth value to 11.
a=np.zeros(10)
a[5]=11
print(a)

[  0.   0.   0.   0.   0.  11.   0.   0.   0.   0.]


In [20]:
#Question 4
#Write a Python program to create a array with values ranging from 12 to 38.
a=np.arange(12,39)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37 38]


In [31]:
#Question 5
#Write a Python program to reverse an array (first element becomes last).
a=np.array([int(x) for x in input().split()])
a=a[::-1]
print('Reversed array is:',a)

4 7 0 3
Reversed array is: [3 0 7 4]


In [32]:
#Question 6
#Write a Python program to an int array converted to a float type.
a=np.array([int(x) for x in input().split()])
a=a.astype(float)
print('Int type array to float type:',a)

1 2 3 4
[ 1.  2.  3.  4.]


In [54]:
#Question 7
#Write a Python program to create a 2d array (5x5) with 1 on the border and 0 inside.
a=np.zeros((5,5))
a[:,0:1]=a[4:5,:]=a[0:1, :]=a[:,4:5]=1
print('Resulting array:',a)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [78]:
#Question 8
#Write a Python program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.
import sys
a=np.array([int(x) for x in input().split()])
print('Number of elements in array:',a.size)
print('Length of one array element in bytes:',sys.getsizeof(a[0]))
print('total bytes consumed by the elements:',sys.getsizeof(a))

1 2 3
Number of elements in array: 3
Length of one array element in bytes: 16
total bytes consumed by the elements: 60


In [83]:
#Question 9
#Write a Python program to create a function cube which cubes all the elements of an array.
a=np.array([int(x) for x in input().split()])
def cube(a):
    return a**3
print('Returned array is:',cube(a))

1 2 3 4
Returned array is: [ 1  8 27 64]


In [109]:
#Question 10
#Write a Python program to how to add an extra column to an numpy array.
a=np.arange(1,26).reshape(5,5)
b=np.zeros((5,1))
a=np.append(a, b, axis=1)
print('New array with extra column:',a)

[[  1.   2.   3.   4.   5.   0.]
 [  6.   7.   8.   9.  10.   0.]
 [ 11.  12.  13.  14.  15.   0.]
 [ 16.  17.  18.  19.  20.   0.]
 [ 21.  22.  23.  24.  25.   0.]]


In [124]:
#Question 11
#Write a Python program to remove the negative values in a numpy array with 0.
a=np.array([int(x) for x in input().split()])
while a[np.argmin(a,axis=0)]<0:
    a[np.argmin(a,axis=0)]=0
print(a)

4 7 -5 8
[4 7 0 8]


In [125]:
#Question 12
#Create a  one dimensional array with 3 elements. Extend the array by repeating the current elements, 3 times.
a=[1,2,3]
a=a*3
print(a)

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [136]:
#Question 13
#Write a Python program compare two arrays using numpy.
print('Enter first array:',end='')
a=np.array([int(x) for x in input().split()])
print('Enter Second array:',end='')
b=np.array([int(x) for x in input().split()])
if np.array_equal(a,b):
    print('These are Same arrays')
else:
    print('These are Different arrays')

Enter first array:1 2 3
Enter Second array:4 6 8
These are Different arrays


In [142]:
#Question 14
#Write a Python program to find the memory size of a NumPy array.
a=np.array([int(x) for x in input().split()])
print('Size of NumPy array in bytes is:',sys.getsizeof(a))

1 2 3 4
Size of NumPy array in bytes is: 64


In [148]:
#Question 15
#Create a 3x5 array with random elements. Reshape this into 5x3.  
a=np.random.random((3,5))
print('Before:\n',a)
a=a.reshape((5,3))
print('\nAfter reshaping:\n',a)

Before:
 [[ 0.42616857  0.49446928  0.89494068  0.38204119  0.358191  ]
 [ 0.26505659  0.10420553  0.12256522  0.25891935  0.31753373]
 [ 0.71765956  0.11860396  0.79093843  0.52271448  0.76307568]]

After reshaping:
 [[ 0.42616857  0.49446928  0.89494068]
 [ 0.38204119  0.358191    0.26505659]
 [ 0.10420553  0.12256522  0.25891935]
 [ 0.31753373  0.71765956  0.11860396]
 [ 0.79093843  0.52271448  0.76307568]]


In [214]:
#Question 16
#Write a Python program to create a 3-D array [6x6x6] with ones on diagonals and zeros elsewhere
a=np.eye(6)
a=np.array([a]*6)
print('Shape of a:',a.shape)
print('\nResulting array:\n',a)

Shape of a: (6, 6, 6)

Resulting array:
 [[[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  0.  0.  0.  1.]]

 [[ 1.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0

#Question 17
The following table includes marks of students in various subjects.  Each row corresponds to a student [ Rajesh, Rima, Ram and Joseph]  coulmn correspond to a subject [Maths, Physics, Chemistry, Sociology]

15 . 20 .   25  12
45 .  50 .  50 . 48
8 .    7 .   3 .    2
28 .  32 . 40 .  39

Do the following 
A.
1. FInd the mean, median, mode and standard deviation for marks of each subject
2. What is the minimum and maximum of each subject?
3. Print the subject in  each student good at and poor at ?
4. What is the overall class mean, mode, median and standard deviation

B.
Teacher just announced the marks of English. They are 40, 49, 10 and 35 for eah student.

Re-calculate all subparts of A.

C. A new student joined the class. For the time being, the scores are going to be zero for each subject. 

Re-calculate A again with the new student.

D. Print the current score card for the class

In [491]:
#Solution 17
from scipy import stats
student=['Rajesh', 'Rima', 'Ram', 'Joseph']              #Rows
subject=['Maths', 'Physics', 'Chemistry', 'Sociology']   #Columns
marks=np.array([[15,20,25,12],  #Rajesh
               [45,50,50,48],  #Rima
               [8,7,3,2],      #Ram
               [28,32,40,39]])  #Joseph

#A.1 
#FInd the mean, median, mode and standard deviation for marks of each subject
print('Mean of marks:')
for sub,m in zip(subject,np.mean(marks,axis=0)):
    print(sub,':',m)

print('\nMedian of marks:')
for sub,med in zip(subject,np.median(marks,axis=0)):
    print(sub,':',med)

print('\nMode of marks:')
for sub,mod in zip(subject,np.transpose(stats.mode(marks,axis=0)[0])):
    print(sub,':',mod[0])
    
print('\nStandard Daviation of marks:')
for sub,sd in zip(subject,np.std(marks,axis=0)):
    print(sub,':',sd)

Mean of marks:
Maths : 24.0
Physics : 27.25
Chemistry : 29.5
Sociology : 25.25

Median of marks:
Maths : 21.5
Physics : 26.0
Chemistry : 32.5
Sociology : 25.5

Mode of marks:
Maths : 8
Physics : 7
Chemistry : 3
Sociology : 2

Standard Daviation of marks:
Maths : 14.0890028036
Physics : 15.8331140336
Chemistry : 17.6988700204
Sociology : 18.8596792125


In [492]:
#A.2
#What is the minimum and maximum of each subject?
print('Subject wise minimum and maximum:')
for sub,mini,maxi in zip(subject,np.min(marks,axis=0),np.max(marks,axis=0)):
    print(sub,':\n\tMin:',mini,'\n\tMax:',maxi)

Subject wise minimum and maximum:
Maths :
	Min: 8 
	Max: 45
Physics :
	Min: 7 
	Max: 50
Chemistry :
	Min: 3 
	Max: 50
Sociology :
	Min: 2 
	Max: 48


In [493]:
#A.3
#Print the subject in  each student good at and poor at ?
print('Subject in  each student good at and poor at:')
for stu,good,bad in zip(student,np.argmax(marks,axis=1),np.argmin(marks,axis=1)):
    print(stu,':\n\tGood:',subject[good],'\n\tPoor:',subject[bad])

Subject in  each student good at and poor at:
Rajesh :
	Good: Chemistry 
	Poor: Sociology
Rima :
	Good: Physics 
	Poor: Maths
Ram :
	Good: Maths 
	Poor: Sociology
Joseph :
	Good: Chemistry 
	Poor: Maths


In [494]:
#A.4
#What is the overall class mean, mode, median and standard deviation
print('Mean of overall class:',np.mean(marks))
print('Median of overall class is:',np.median(marks))
print('Mode of marks:',stats.mode(marks,axis=None)[0][0])

Mean of overall class: 26.5
Median of overall class is: 26.5
Mode of marks: 50


In [495]:
#Question B
#B.Teacher just announced the marks of English. They are 40, 49, 10 and 35 for eah student.
subject=np.append(subject,['English'])
marks=np.append(marks,[[40],[49],[10],[35]],axis=1)
print('New subjects:\n',subject)
print('\nNew Marks\n',marks)

New subjects:
 ['Maths' 'Physics' 'Chemistry' 'Sociology' 'English']

New Marks
 [[15 20 25 12 40]
 [45 50 50 48 49]
 [ 8  7  3  2 10]
 [28 32 40 39 35]]


In [496]:
#B.1 
#Find the mean, median, mode and standard deviation for marks of each subject
print('Mean of marks:')
for sub,m in zip(subject,np.mean(marks,axis=0)):
    print(sub,':',m)

print('\nMedian of marks:')
for sub,med in zip(subject,np.median(marks,axis=0)):
    print(sub,':',med)

print('\nMode of marks:')
for sub,mod in zip(subject,np.transpose(stats.mode(marks,axis=0)[0])):
    print(sub,':',mod[0])
    
print('\nStandard Daviation of marks:')
for sub,sd in zip(subject,np.std(marks,axis=0)):
    print(sub,':',sd)

Mean of marks:
Maths : 24.0
Physics : 27.25
Chemistry : 29.5
Sociology : 25.25
English : 33.5

Median of marks:
Maths : 21.5
Physics : 26.0
Chemistry : 32.5
Sociology : 25.5
English : 37.5

Mode of marks:
Maths : 8
Physics : 7
Chemistry : 3
Sociology : 2
English : 10

Standard Daviation of marks:
Maths : 14.0890028036
Physics : 15.8331140336
Chemistry : 17.6988700204
Sociology : 18.8596792125
English : 14.4654761415


In [497]:
#B.2
#What is the minimum and maximum of each subject?
print('Subject wise minimum and maximum:')
for sub,mini,maxi in zip(subject,np.min(marks,axis=0),np.max(marks,axis=0)):
    print(sub,':\n\tMin:',mini,'\n\tMax:',maxi)

Subject wise minimum and maximum:
Maths :
	Min: 8 
	Max: 45
Physics :
	Min: 7 
	Max: 50
Chemistry :
	Min: 3 
	Max: 50
Sociology :
	Min: 2 
	Max: 48
English :
	Min: 10 
	Max: 49


In [498]:
#B.3
#Print the subject in  each student good at and poor at ?
print('Subject in  each student good at and poor at:')
for stu,good,bad in zip(student,np.argmax(marks,axis=1),np.argmin(marks,axis=1)):
    print(stu,':\n\tGood:',subject[good],'\n\tPoor:',subject[bad])

Subject in  each student good at and poor at:
Rajesh :
	Good: English 
	Poor: Sociology
Rima :
	Good: Physics 
	Poor: Maths
Ram :
	Good: English 
	Poor: Sociology
Joseph :
	Good: Chemistry 
	Poor: Maths


In [499]:
#B.4
#What is the overall class mean, mode, median and standard deviation
print('Mean of overall class:',np.mean(marks,axis=None))
print('Median of overall class is:',np.median(marks,axis=None))
print('Mode of marks:',stats.mode(marks,axis=None)[0][0])


Mean of overall class: 27.9
Median of overall class is: 30.0
Mode of marks: 40


In [500]:
#C
#A new student joined the class. For the time being, the scores are going to be zero for each subject. 
student=np.append(student,['Sita'])
zeros=np.zeros(5)
marks=np.vstack([marks,zeros])
print('Students now:\n',student)
print('\nMarks now\n',marks)

Students now:
 ['Rajesh' 'Rima' 'Ram' 'Joseph' 'Sita']

Marks now
 [[ 15.  20.  25.  12.  40.]
 [ 45.  50.  50.  48.  49.]
 [  8.   7.   3.   2.  10.]
 [ 28.  32.  40.  39.  35.]
 [  0.   0.   0.   0.   0.]]


In [501]:
#C.1 
#Find the mean, median, mode and standard deviation for marks of each subject
print('Mean of marks:')
for sub,m in zip(subject,np.mean(marks,axis=0)):
    print(sub,':',m)

print('\nMedian of marks:')
for sub,med in zip(subject,np.median(marks,axis=0)):
    print(sub,':',med)

print('\nMode of marks:')
for sub,mod in zip(subject,np.transpose(stats.mode(marks,axis=0)[0])):
    print(sub,':',mod[0])
    
print('\nStandard Daviation of marks:')
for sub,sd in zip(subject,np.std(marks,axis=0)):
    print(sub,':',sd)

Mean of marks:
Maths : 19.2
Physics : 21.8
Chemistry : 23.6
Sociology : 20.2
English : 26.8

Median of marks:
Maths : 15.0
Physics : 20.0
Chemistry : 25.0
Sociology : 12.0
English : 35.0

Mode of marks:
Maths : 0.0
Physics : 0.0
Chemistry : 0.0
Sociology : 0.0
English : 0.0

Standard Daviation of marks:
Maths : 15.8417170787
Physics : 17.870646323
Chemistry : 19.7443662851
Sociology : 19.6611291639
English : 18.626862323


In [502]:
#C.2
#What is the minimum and maximum of each subject?
print('Subject wise minimum and maximum:')
for sub,mini,maxi in zip(subject,np.min(marks,axis=0),np.max(marks,axis=0)):
    print(sub,':\n\tMin:',mini,'\n\tMax:',maxi)

Subject wise minimum and maximum:
Maths :
	Min: 0.0 
	Max: 45.0
Physics :
	Min: 0.0 
	Max: 50.0
Chemistry :
	Min: 0.0 
	Max: 50.0
Sociology :
	Min: 0.0 
	Max: 48.0
English :
	Min: 0.0 
	Max: 49.0


In [503]:
#C.3
#Print the subject in  each student good at and poor at ?
print('Subject in  each student good at and poor at:')
for stu,good,bad in zip(student,np.argmax(marks,axis=1),np.argmin(marks,axis=1)):
    print(stu,':\n\tGood:',subject[good],'\n\tPoor:',subject[bad])

Subject in  each student good at and poor at:
Rajesh :
	Good: English 
	Poor: Sociology
Rima :
	Good: Physics 
	Poor: Maths
Ram :
	Good: English 
	Poor: Sociology
Joseph :
	Good: Chemistry 
	Poor: Maths
Sita :
	Good: Maths 
	Poor: Maths


In [504]:
#C.4
#What is the overall class mean, mode, median and standard deviation
print('Mean of overall class:',np.mean(marks,axis=None))
print('Median of overall class is:',np.median(marks,axis=None))
print('Mode of marks:',stats.mode(marks,axis=None)[0][0])

Mean of overall class: 22.32
Median of overall class is: 20.0
Mode of marks: 0.0


In [554]:
#D
#Print the current score card for the class
Totals=np.sum(marks,axis=1)
topScorer=student[np.argmax(Totals)]
leastScorer=student[(np.argmin(Totals))]
print('Student with best scores:',topScorer,':',np.max(Totals))
print('Student with lowest scores:',leastScorer,':',np.min(Totals))

dic={}
i=0
for stu in student:
    dic[stu]=Totals[i]
    i+=1
    
li=sorted(dic.values(),reverse=True)
print('\nSorted result of students:')
for y in li:
    for x in dic:
        if dic[x]==y:
            print(x,':',dic[x])

print('\nScore card of the class is:')
i=0
for stu in student:
    print(stu,':')
    for sub,mark in zip(subject,marks[i]):
        print('\t',sub,':',mark)
    print('Total:',Totals[i],'\n')
    i+=1


Student with best scores: Rima : 242.0
Student with lowest scores: Sita : 0.0

Sorted result of students:
Rima : 242.0
Joseph : 174.0
Rajesh : 112.0
Ram : 30.0
Sita : 0.0

Score card of the class is:
Rajesh :
	 Maths : 15.0
	 Physics : 20.0
	 Chemistry : 25.0
	 Sociology : 12.0
	 English : 40.0
Total: 112.0 

Rima :
	 Maths : 45.0
	 Physics : 50.0
	 Chemistry : 50.0
	 Sociology : 48.0
	 English : 49.0
Total: 242.0 

Ram :
	 Maths : 8.0
	 Physics : 7.0
	 Chemistry : 3.0
	 Sociology : 2.0
	 English : 10.0
Total: 30.0 

Joseph :
	 Maths : 28.0
	 Physics : 32.0
	 Chemistry : 40.0
	 Sociology : 39.0
	 English : 35.0
Total: 174.0 

Sita :
	 Maths : 0.0
	 Physics : 0.0
	 Chemistry : 0.0
	 Sociology : 0.0
	 English : 0.0
Total: 0.0 

